### ISSUE TITLE
build的时候会一直卡住

### ISSUE THREAD

**Issue by liuwm91** [netease-im/NIM_Web_Demo_H5#1]
build到一半的时候会卡住，不能完成了
![qq 20170531162733](https://cloud.githubusercontent.com/assets/6902289/26622843/5353355e-461e-11e7-9d0d-608d7484a9f2.png)

**Comment by king3366ster** [comment]
webpack配置了watch 选项，侦听文件变化，这样可以动态编译生成，修改文件实时生效，而不需要每次改完文件重新去build。
截图这样说明已经build完成啦，他会侦听你对文件的操作，所以没有把控制器交回给控制台

**Comment by liuwm91** [comment]
原来如此。感谢~
