### ISSUE TITLE
进入聊天界面报错和无法进入聊天室

### ISSUE THREAD

**Issue by ghost** [netease-im/NIM_Web_Demo_H5#3]
克隆master分支的代码到本地，执行如下命令：
<img width="1408" alt="terminal" src="https://user-images.githubusercontent.com/28668354/30239472-1e84da46-9590-11e7-913e-90e38d68ee37.png">
打开http://localhost:2001/webdemo/h5/index.html。进入聊天页面时如下错误
<img width="1759" alt="issue1" src="https://user-images.githubusercontent.com/28668354/30239483-5888051a-9590-11e7-91c9-16148f7f3ef6.png">
以及无法进入聊天室
<img width="1759" alt="issue2" src="https://user-images.githubusercontent.com/28668354/30239485-6674a35e-9590-11e7-971c-c6a05ceba0d8.png">

**Comment by king3366ster** [comment]
错误代码是sdk没有载入，下一遍新的代码看看
