### ISSUE TITLE
真机测试

### ISSUE THREAD

**Issue by ghost** [netease-im/NIM_Web_Demo_H5#4]
本机ip
<img width="672" alt="issue4" src="https://user-images.githubusercontent.com/28668354/30239493-9646ebaa-9590-11e7-92f1-74c622687762.png">
修改index.html等页面注释的代码
<img width="783" alt="issue5" src="https://user-images.githubusercontent.com/28668354/30239496-a3d69dec-9590-11e7-9f86-d122634a66aa.png">
执行如下命令
<img width="751" alt="terminal2" src="https://user-images.githubusercontent.com/28668354/30239491-83959d3a-9590-11e7-9dc5-d2a1392cb301.png">
打开手机http://192.168.0.104:2002/webdemo/h5/index.html
![issue3](https://user-images.githubusercontent.com/28668354/30239498-b373d486-9590-11e7-9b57-d4f3c2ac2c6a.PNG)

**Comment by king3366ster** [comment]
2002是weinre的配置，直接访问真实端口，譬如http://192.168.0.104:2001/webdemo/h5/index.html
