### ISSUE TITLE
这个不能视频通话吗？

### ISSUE THREAD

**Issue by DmcSDK** [netease-im/NIM_Web_Demo_H5#41]

**Comment by Claiyre** [comment]
暂时没有喔，可以参考开发文档集成～

https://dev.yunxin.163.com/docs/product/%E9%9F%B3%E8%A7%86%E9%A2%91%E9%80%9A%E8%AF%9D2.0/%E4%BA%A7%E5%93%81%E6%A6%82%E8%BF%B0/%E4%BA%A7%E5%93%81%E6%80%BB%E4%BD%93%E6%A6%82%E8%BF%B0
