### ISSUE TITLE
npm run dev/prod 报错 无法打包

### ISSUE THREAD

**Issue by jhgrrewq** [netease-im/NIM_Web_Demo_H5#6]
![vux-error](http://owfk4l3hc.bkt.clouddn.com/%E5%B1%8F%E5%B9%95%E5%BF%AB%E7%85%A7%202017-09-17%20%E4%B8%8B%E5%8D%8811.07.28.png)

npm install 安装依赖后 npm run dev 显示报错vux有个文件没有对应的loader，看了一下那个文件是vux的源码的css文件。这是怎么回事

**Comment by king3366ster** [comment]
这个可能是vux更新了新的版本，出现了一些不兼容，可以考虑把vux组件库进行更新，或者用yarn指定版本安装包依赖，npm这个问题确实挺头疼的

2017-09-17 23:28 GMT+08:00 jack <notifications@github.com>:

**Comment by jhgrrewq** [comment]
你之前的版本依赖能运行吗？ 我按照你的版本报错，然后vux和vux-loader都更新到最新后还是同样的问题

**Comment by king3366ster** [comment]
固定vux版本，这是vux高版本的bug，已在demo代码中做了版本限制（重新npm i即可）

**Comment by jhgrrewq** [comment]
我自己重新用vux脚手架新建了项目，将你的代码进行了整合，可以运行。确实是低版本vux可以
