### ISSUE TITLE
执行 npm run dev 报错/无法打包

### ISSUE THREAD

**Issue by zhuchongju** [netease-im/NIM_Web_Demo_H5#7]
运行 npm run dev 时候报错，提示css-loader好像下载有问题
![_20170919105154](https://user-images.githubusercontent.com/32084144/30573846-aa7f9154-9d28-11e7-804c-53f13656b161.png)

**Comment by king3366ster** [comment]
固定vux版本，这是vux高版本的bug，已在demo代码中做了版本限制（重新npm i即可）
